name: CI/CD Simulation

on:
  push:
    branches: ["main"]

jobs:
  simulate-process:
    runs-on: ubuntu-latest
    steps:
      - name: Simulasi Penyiapan Sistem
        run: echo "Menyiapkan lingkungan..."

      - name: Simulasi Pengujian Kode
        run: echo "Pengujian otomatis berhasil..."

      - name: Simulasi Deployment
        run: echo "Kode berhasil dipublikasikan ke peladen!"