name: CI/CD Warehouse

on:
  push:
    branches: ["main"]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: '8.2'
          extensions: mbstring, xml, bcmath, curl
          tools: composer

      - name: Remove composer.lock (Force Refresh)
        run: rm -f composer.lock

      - name: Install Dependencies
        run: composer update --no-interaction --prefer-dist --ignore-platform-reqs

      - name: Check PHP and Composer
        run: |
          php -v
          composer --version